`SELECT TOP (1000) [row_id]
      ,[item_guid]
      ,[proprietary_name]
      ,[NDC]
      ,[strength]
      ,[dosage_form]
      ,[route]
      ,[manufacturer]
      ,[product_NDC]
      ,[nonproprietary_name]
      ,[substance_name]
      ,[product_type_name]
      ,[packagedescription]
      ,[pharm_class]
      ,[drug_class]
      ,[NDC_language]
  FROM [Quantaira_Device_LocalDB].[web].[items]`;
